/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.foobarspam.cotxox.main;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Cotxox classUnderTest = new Cotxox();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
